name: Upload Files to S3 on Push

on:
  push:
    branches:
      - main

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload Files to S3
        run: |
          aws s3 cp . s3://fullautomatedbucket1/scripts/ --recursive --exclude ".git/*"
